config/routes.rb
Rails.application.routes.draw do


  resources :parts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :parts, only: [:index]
  get '/', to: 'parts#index'

  get '/manage_my_parts_like_a_mofo', to: 'parts#index_for_admin'

  get '/parts_that_are_available', to: 'parts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/part.rb
class Part < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  def index_for_admin
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:year, :make, :model, :name, :description, :condition, :price, :imgurl)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KraigsCarParts</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
  <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
  <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <div class="button button-outline">

    <%= link_to 'GO TO PARTS LIST', parts_that_are_available_path %>
  </div>

<div class="header-area">
  <marquee>USE YOUR BROWSER'S 'FIND' FEATURE TO SEARCH THIS DATABASE OF PARTS. THIS LIST IS UPDATED DAILY.</marquee>
  <p class="center-text">SEE A PART YOU ARE INTERESTED IN? TEXT OR CALL <strong>(720)276-1450</strong></p>
  <p class="center-text">We do installation, part replacement and other automotive mechanical work at VERY reasonable rates in the South Denver area.</p>
</div>

  <%= yield %>
</body>
</html>

app/views/parts/_form.html.erb
<%= form_with(model: part, local: true) do |form| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :part_year %>
  </div>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make, id: :part_make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :part_model %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :part_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :part_description %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition, id: :part_condition %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :part_price %>
  </div>

  <div class="field">
    <%= form.label :imgurl %>
    <%= form.text_field :imgurl, id: :part_imgurl %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<div class="button button-outline">
  <%= link_to 'Show', @part %>
</div>

<div class="button button-outline">
  <%= link_to 'Back', parts_path %>
</div>

app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="center-text">PARTS CURRENTLY AVAILABLE</h2>

<table>
  <thead>
    <tr>
      <th>Part Number</th>
      <th>Year</th>
      <th>Make</th>
      <th>Model</th>
      <th>Name</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Img</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td class="bold-data"><%= "%05d" % part.id %></td>
        <td><%= part.year %></td>
        <td><%= part.make %></td>
        <td><%= part.model %></td>
        <td><%= part.name %></td>
        <td><%= part.condition %></td>
        <td><%= '%.2f' % part.price %></td>
        <td><img class="tiny-thumb" src="<%= part.imgurl %>" alt=""> </td>
        <td><%= link_to 'Show Part Info', part %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/parts/index_for_admin.html.erb
<p id="notice"><%= notice %></p>

<h1>KRAIGS ADMIN MENU</h1>

<table>
  <thead>
    <tr>
      <th>Part Number</th>
      <th>Year</th>
      <th>Make</th>
      <th>Model</th>
      <th>Name</th>
      <!-- <th>Description</th> -->
      <th>Condition</th>
      <th>Price</th>
      <th>Img</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= "%05d" % part.id %></td>
        <td><%= part.year %></td>
        <td><%= part.make %></td>
        <td><%= part.model %></td>
        <td><%= part.name %></td>
        <!-- <td><%= part.description %></td> -->
        <td><%= part.condition %></td>
        <td><%= '%.2f' % part.price %></td>
        <td><img class="tiny-thumb" src="<%= part.imgurl %>" alt=""> </td>
        <td><%= link_to 'Show Part', part %></td>
        <td><%= link_to 'Edit Part', edit_part_path(part) %></td>
        <td><%= link_to 'Delete Part', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="button button-outline">
  <%= link_to 'New Part', new_part_path %>
</div>

app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form', part: @part %>

<div class="button button-outline">
  <%= link_to 'Back to Parts Management List', manage_my_parts_like_a_mofo_path %>
</div>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @part.name + " from a " + @part.year.to_s + " - " + @part.make + " " + @part.model%></h1>
</p>

<h3>
  <strong>Part Description:</strong>
  <h5><%= @part.description %></h5>
</h3>

<h3>
  <strong>Condition:</strong>
  <%= @part.condition %>
</h3>

<h3>
  <strong>Price:</strong>
  <%= "$" + ('%.2f' % @part.price).to_s %>
</h3>

<p>
  <strong>Part Image:</strong>
  <br>
  <img src="<%= @part.imgurl %>" class="show-img" alt="">
</p>